// <auto-generated />
using System;
using ApiGtt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace apigtt.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20190213185824_SomeChangesMigration")]
    partial class SomeChangesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ApiGtt.Models.Certificates", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("alias");

                    b.Property<string>("clientName");

                    b.Property<string>("content");

                    b.Property<string>("emailRenov");

                    b.Property<string>("entity");

                    b.Property<DateTime>("expireDate");

                    b.Property<long>("idOrg");

                    b.Property<string>("name");

                    b.Property<bool>("notice");

                    b.Property<string>("observations");

                    b.Property<string>("password");

                    b.Property<string>("repo");

                    b.Property<string>("serialNum");

                    b.Property<string>("subject");

                    b.Property<bool>("ticketed");

                    b.HasKey("id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("ApiGtt.Models.Jira", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("component");

                    b.Property<string>("description");

                    b.Property<long>("iduser");

                    b.Property<string>("issuer");

                    b.Property<string>("password");

                    b.Property<string>("proyect");

                    b.Property<string>("url");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Jira");
                });

            modelBuilder.Entity("ApiGtt.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("password");

                    b.Property<string>("role");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
